### ISSUE TITLE
[1.18.2] Goblin Stronghold generates outside the bounds of the dark forest

### ISSUE THREAD

**Issue by EvergreenSystems** [TeamTwilight/twilightforest#1487]
### Forge Version

40.1.19

### Twilight Forest Version

1.18.2-4.1.1010

### Steps to Reproduce

1. Locate a dark forest, and a goblin stronghold
2. Observe the stream around the forest for the protruding stronghold

### What You Expected

The goblin stronghold to generate within the bounds of the dark forest

### What Happened Instead

The goblin stronghold will cut out into the stream, and sometimes well into the bank of the adjacent biome

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
Is this on a FRESH world with the latest update? Because this was fixed a while ago.

**Comment by EvergreenSystems** [comment]
Not a fresh world, but a fresh TF dim (deleted twilight forest dimension folder). Apparently that doesn't suffice if the issue is persisting

**Comment by EvergreenSystems** [comment]
Upon generating a new world the issue does not persist, my bad

**Comment by GizmoTheMoonPig** [comment]
Unfortunately, this does still happen, it's just much rarer now. The structure offset on the biome grid is sometimes too big, and it'll generate close to the stream or dark forest center. 

There's 2 ways to go about fixing this: make the stronghold even smaller, or change the offsets that structures have. The thing is, we don't want to really do either of those. I already shrunk the stronghold a little bit, but I don't want to shrink it too much. 

Labeling as won't fix as the structure rework will solve this issue, but it's not a huge problem atm in my eyes
(this was typed before your last comment lol, was just finalizing it)
